version: '3.9'

services:
  backend:
    build: ./backend
    container_name: topnotch_backend
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: topnotch_frontend
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: topnotch_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

